force-app/main/default/objects/Branch_Relationship_Officer__c/Branch_Relationship_Officer__c.object-meta.xml
<CustomObject>
    <description>Her subede (Branch )gorevli olan Relation Officer bilgisi bu object te tutulacaktir</description>
    <label>Branch-Relationship Officer</label>
    <nameField>
        <displayFormat>BRO-{00000}</displayFormat>
        <label>Branch-Relationship Officer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Branch-Relationship Officers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Branch_Relationship_Officer__c/fields/Branch_Name__c.field-meta.xml
<CustomField>
    <fullName>Branch_Name__c</fullName>
    <label>Branch Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Alabama</fullName>
            </value>
            <value>
                <fullName>Alaska</fullName>
            </value>
            <value>
                <fullName>Arizona</fullName>
            </value>
            <value>
                <fullName>California</fullName>
            </value>
            <value>
                <fullName>Colorado</fullName>
            </value>
            <value>
                <fullName>Connecticut</fullName>
            </value>
            <value>
                <fullName>Florida</fullName>
            </value>
            <value>
                <fullName>Georgia</fullName>
            </value>
            <value>
                <fullName>Hawaii</fullName>
            </value>
            <value>
                <fullName>Missouri</fullName>
            </value>
            <value>
                <fullName>Montana</fullName>
            </value>
            <value>
                <fullName>Nevada</fullName>
            </value>
            <value>
                <fullName>New York</fullName>
            </value>
            <value>
                <fullName>North Carolina</fullName>
            </value>
            <value>
                <fullName>North Dakota</fullName>
            </value>
            <value>
                <fullName>Oregon</fullName>
            </value>
            <value>
                <fullName>Texas</fullName>
            </value>
            <value>
                <fullName>Washington</fullName>
            </value>
            <value>
                <fullName>West Virginia</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Branch_Relationship_Officer__c/fields/Relationship_Officer__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Officer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Branch ta calisacak Officer bilgilerini tutacak</description>
    <label>Relationship Officer</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Branch_Relationship_Officers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FD_Details__c/FD_Details__c.object-meta.xml
<CustomObject>
    <description>Fixed deposite (Mevduat Hesabi) bilgilerini tutan object</description>
    <label>FD Details</label>
    <nameField>
        <displayFormat>FD-{00000}</displayFormat>
        <label>FD Details Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FD Details</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/FD_Details__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <label>Branch</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Alabama</fullName>
            </value>
            <value>
                <fullName>Alaska</fullName>
            </value>
            <value>
                <fullName>Arizona</fullName>
            </value>
            <value>
                <fullName>California</fullName>
            </value>
            <value>
                <fullName>Colorado</fullName>
            </value>
            <value>
                <fullName>Connecticut</fullName>
            </value>
            <value>
                <fullName>Florida</fullName>
            </value>
            <value>
                <fullName>Georgia</fullName>
            </value>
            <value>
                <fullName>Hawaii</fullName>
            </value>
            <value>
                <fullName>Missouri</fullName>
            </value>
            <value>
                <fullName>Montana</fullName>
            </value>
            <value>
                <fullName>Nevada</fullName>
            </value>
            <value>
                <fullName>New York</fullName>
            </value>
            <value>
                <fullName>North Carolina</fullName>
            </value>
            <value>
                <fullName>North Dakota</fullName>
            </value>
            <value>
                <fullName>Oregon</fullName>
            </value>
            <value>
                <fullName>Texas</fullName>
            </value>
            <value>
                <fullName>Washington</fullName>
            </value>
            <value>
                <fullName>West Virginia</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FD_Details__c/fields/Relationship_Officer__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Officer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Relationship Officer</label>
    <referenceTo>User</referenceTo>
    <relationshipName>FD_Details1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/FixedDepositTriggerHandler.cls
public class FixedDepositTriggerHandler {
    
    public static void populateRelOfficer(List<FD_Details__c> fdList){
        //Brach-Relation Officer objectinden sorgulanacak Branclar colection haline getirildi.
        Set<String> branchNames = new Set<String>();
        for(FD_Details__c fd : fdList){
            if(String.isNotBlank(fd.Branch__c)){
                branchNames.add(fd.Branch__c);
            }
            
        }
        //İlgili branchlarda gögrevli Relationship Officer bilgileri sorgu ile çekilir
        List<Branch_Relationship_Officer__c> broList = [SELECT Id, Branch_Name__c, Relationship_Officer__c
                                                       FROM Branch_Relationship_Officer__c
                                                       WHERE Branch_Name__c IN :branchNames];
        
      //Branch-RO eşleştirilmesini Map formata çevirelim. Bu sayede MAp in kullanaışlı methodlarından faydalanabiliriz Ör:get()
      
        Map<String, String> branchRelMap = new Map<String, String>();
        for(Branch_Relationship_Officer__c bro : broList){
            branchRelMap.put(bro.Branch_Name__c, bro.Relationship_Officer__c);
        }
        
        //FD Details objectindeki Relationship Officer fieldına, Master objecten çekilen Relationship Officer bilgisini atayalım.
        for(FD_Details__c fd : fdList){
            if(String.isNotBlank(fd.Branch__c)){
                fd.Relationship_Officer__c = branchRelMap.get(fd.Branch__c);
                
            }
        }
    }
    
    public static void shareWithRelOfficerAfterInsert(List<FD_Details__c> fdList){
        
        List<FD_Details__Share> fdsList = new List<FD_Details__Share>();
        for(FD_Details__c fd : fdList){
            if(String.isNotBlank(fd.Relationship_Officer__c)){
                
              fdsList.add(createShareInstance(fd.Id,fd.Relationship_Officer__c));
               
            }
            if(String.isNotBlank(fd.Sales_Representative__c)){
                
              fdsList.add(createShareInstance(fd.Id,fd.Sales_Representative__c));
               
            }
        }
        Database.insert(fdsList, false);
    }
    
    
    public static void shareWithRelOfficerAfterUpdate(List<FD_Details__c> fdList ,Map<Id,FD_Details__c>fdOldMap){
        
         List<FD_Details__Share> fdsList = new List<FD_Details__Share>();
           List<FD_Details__Share> fdsOldToDelete = new List<FD_Details__Share>();
        for(FD_Details__c fd : fdList){
            //Relationship Officer bilgisinin degistigini kontrol ediyoruz .
            if(String.isNotBlank(fd.Relationship_Officer__c) && fd.Relationship_Officer__c!=fdOldMap.get(fd.Id).Relationship_Officer__c){
                //Share Object ine eklenecek yeni instance olusturuyoruz.
                fdsList.add(createShareInstance(fd.Id,fd.Relationship_Officer__c));
                
                List<FD_Details__Share>fdsOld =[SELECT Id, RowCause
                                                FROM FD_Details__Share 
                                                WHERE ParentId=:fd.Id 
                                                AND UserOrGroupId =:fdOldMap.get(fd.Id).Relationship_Officer__c 
                                                AND RowCause='Manual'];
                                                           
                if(fdsOld!=null){
                    fdsOldToDelete.addAll(fdsOld);
                }
               
            }
             if(String.isNotBlank(fd.Sales_Representative__c) && fd.Sales_Representative__c!=fdOldMap.get(fd.Id).Relationship_Officer__c){
                //Share Object ine eklenecek yeni instance olusturuyoruz.
                fdsList.add(createShareInstance(fd.Id,fd.Sales_Representative__c));
                
                List<FD_Details__Share>fdsOld2 =[SELECT Id, RowCause
                                                FROM FD_Details__Share 
                                                WHERE ParentId=:fd.Id 
                                                AND UserOrGroupId =:fdOldMap.get(fd.Id).Sales_Representative__c
                                                AND RowCause='Manual'];
                                                           
                if(fdsOld2!=null){
                    fdsOldToDelete.addAll(fdsOld2);
                }
               
            }
        }
       
        Database.insert(fdsList,false);
        Database.delete(fdsOldToDelete,false);
    }
    
    private static  FD_Details__Share createShareInstance(String parentId , String userOrGroupId){
        FD_Details__Share fds = new FD_Details__Share();
                fds.ParentId = parentId;
                fds.UserOrGroupId = UserOrGroupId;
                fds.AccessLevel = 'Read'; //Read veya Edit yazılabilir
                fds.RowCause = 'Manual'; //her zaman Manual girilir
        return fds;
    }
    
    
    
    
    
    
    
    
    
    
    
    
    
}